#!/bin/bash
#######################################################
# HocVPS Script Installer v1.5
# To install HocVPS Script type:
# curl -sO https://lic.cgt.vn/HocVPS/install && bash install
#######################################################

chattr -i /etc/selinux/config
sed -i 's/SELINUX=enforcing/SELINUX=disabled/g' /etc/selinux/config
sed -i 's/nameserver/#nameserver/g' /etc/resolv.conf 
echo "nameserver 8.8.8.8" >> /etc/resolv.conf

if [ $(id -u) != "0" ]; then
    echo "You need to be root to perform this command. Run \"sudo su\" to become root!"
    exit
fi
if [ -f /var/cpanel/cpanel.config ]; then
clear
echo "Your server installed WHM/Cpanel, please reinstall to use HocVPS Script."
exit
fi

if [ -f /etc/psa/.psa.shadow ]; then
clear
echo "Your server installed Plesk, please reinstall to use HocVPS Script."
exit
fi

if [ -f /etc/init.d/directadmin ]; then
clear
echo "Your server installed DirectAdmin, please reinstall to use HocVPS Script."
exit
fi

if [ -f /etc/init.d/webmin ]; then
clear
echo "Your server installed Webmin, please reinstall to use HocVPS Script."
exit
fi

if [[ -z "$(cat /etc/resolv.conf)" ]]; then
        echo ""
        echo "/etc/resolv.conf is empty. No nameserver resolvers detected !! "
        echo "Please configure your /etc/resolv.conf correctly or you will not"
        echo "be able to use the internet or download from your server."
        echo "aborting script... please re-run install"
        echo ""
        exit
fi

ls -lah /etc/redhat-release > /dev/null 2>&1
if [ "$?" = "0" ]; then

os=$(cat /etc/redhat-release  | awk '{print $1}')

if [ "$os" = "CentOS" ]; then
centos_version=$(rpm -E %centos)
elif [ "$os" = "Rocky" ]; then
centos_version=$(rpm -E %rocky)
elif [ $os = "AlmaLinux" ]; then
centos_version=$(rpm -E %almalinux)
fi

#os_ubuntu=`cat /etc/lsb-release | grep DISTRIB_RELEASE | cut -d= -f2`

if [ "$centos_version" != "7" ] && [ "$centos_version" != "8" ]; then
        echo "HocVPS Script is only compatible with CentOS 7 or Centos 8 or RockyLinux8"
        echo "aborting script..."
        exit
fi

if [ -f /etc/hocvps/scripts.conf ]; then
        echo "========================================================================="
        echo "Server/VPS cua ban da cai san HocVPS Script"
        echo "Hay su dung lenh hocvps de truy cap menu quan ly"
        echo "Chao tam biet !"
        echo "========================================================================="
exit
fi

rm -f install*

cd /root/

rm -f install*

#if [ "$os" = "CentOS" ] then
if [ "$1" = "wordpress" ]; then
	curl -sO https://raw.githubusercontent.com/cgtmedia/TEST/main/scripts/$centos_version/install.sh && bash install.sh wordpress
else
	curl -sO https://raw.githubusercontent.com/cgtmedia/TEST/main/scripts/$centos_version/install.sh && bash install.sh
fi

else
os=$(cat /etc/lsb-release | grep "DISTRIB_ID" | cut -d= -f2)
os_ubuntu=`cat /etc/lsb-release | grep DISTRIB_RELEASE | cut -d= -f2`

if [ "$os_ubuntu" != "18.04" ] && [ "$os_ubuntu" != "20.04" ]; then
        echo "HocVPS Script is only compatible with Ubuntu18.04 or Ubuntu20.04"
        echo "aborting script..."
        exit
fi

if [ -f /etc/hocvps/scripts.conf ]; then
        echo "========================================================================="
        echo "Server/VPS cua ban da cai san HocVPS Script"
        echo "Hay su dung lenh hocvps de truy cap menu quan ly"
        echo "Chao tam biet !"
        echo "========================================================================="
exit
fi

rm -f install*

cd /root/

rm -f install*

#if [ "$os" = "Ubuntu" ] then

curl -sO https://raw.githubusercontent.com/cgtmedia/TEST/main/scripts/ubuntu2004/install.sh
chmod +x install.sh
curl -sO https://raw.githubusercontent.com/cgtmedia/TEST/main/scripts/ubuntu2004/install2.sh && bash install2.sh
#fi
fi
